### ISSUE TITLE
Invisible model mpo700 on Melodic+Gazebo

### ISSUE THREAD

**Issue by YusseffRuiz** [neobotix/neo_mpo_700#2]
I'm having some issues when running the basic simulation or even a spawn of the model MPO700.
The robot appears invisible, i can select it, it can move with the teleoperation keys but is not appearing on the simulation. I wonder if this is a known issue? Or Is it a limitation? I'm applying the logs when running the file.

roslaunch neo_simulation mpo_700_simulation_basic.launch 
... logging to /home/yusseff/.ros/log/591e6e84-96aa-11e9-9990-38378bf463ab/roslaunch-yusseff-MACH-WX9-17099.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
when processing file: /home/yusseff/catkin_ws/src/neo_simulation/robots/mpo_700/mpo_700.urdf.xacro

xacro.py is deprecated; please use xacro instead
started roslaunch server http://yusseff-MACH-WX9:42647/

SUMMARY
========

PARAMETERS
 * /cob_scan_unifier/input_scans: ['/sick_front/sca...
 * /cob_scan_unifier/loop_rate: 100
 * /gazebo/enable_ros_network: True
 * /joint_state_publisher/rate: 20.0
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 20.0
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    mpo_700_spawn (gazebo_ros/spawn_model)
    robot_state_publisher (robot_state_publisher/state_publisher)
    teleop_keyboard (teleop_twist_keyboard/teleop_twist_keyboard.py)
  /cob_scan_unifier/
    scan_unifier_node (cob_scan_unifier/scan_unifier_node)

auto-starting new master
process[master]: started with pid [17112]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 591e6e84-96aa-11e9-9990-38378bf463ab
process[rosout-1]: started with pid [17123]
started core service [/rosout]
process[gazebo-2]: started with pid [17130]
process[gazebo_gui-3]: started with pid [17135]
process[mpo_700_spawn-4]: started with pid [17140]
process[joint_state_publisher-5]: started with pid [17141]
process[robot_state_publisher-6]: started with pid [17142]
ERROR: cannot launch node of type [cob_scan_unifier/scan_unifier_node]: cob_scan_unifier
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/yusseff/Neobotix/src
ROS path [2]=/home/yusseff/catkin_ws/src
ROS path [3]=/opt/ros/melodic/share
process[teleop_keyboard-8]: started with pid [17143]
[ INFO] [1561399400.744329530]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1561399400.745995689]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1561399400.834135715]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1561399400.835230274]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...

Reading from the keyboard  and Publishing to Twist!
---------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .

For Holonomic mode (strafing), hold down the shift key:
---------------------------
   U    I    O
   J    K    L
   M    <    >

t : up (+z)
b : down (-z)

anything else : stop

q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%

CTRL-C to quit

currently:	speed 0.5	turn 1.0 
[INFO] [1561399401.160104, 0.000000]: Loading model XML from ros parameter robot_description
            [INFO] [1561399401.167851, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
              [ INFO] [1561399401.288762680, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
                                                     [ INFO] [1561399401.309820195, 0.042000000]: Physics dynamic reconfigure ready.
                                                    [INFO] [1561399401.473624, 0.199000]: Calling service /gazebo/spawn_urdf_model
                                                  [ INFO] [1561399401.889845997, 0.353000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
                                                                  [ INFO] [1561399401.889941040, 0.353000000]: Starting Laser Plugin (ns = /)
                                                             [ INFO] [1561399401.891257684, 0.353000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
                                                                        [ INFO] [1561399402.077561011, 0.353000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
        [ INFO] [1561399402.077610221, 0.353000000]: Starting Laser Plugin (ns = /)
   [INFO] [1561399402.078390, 0.353000]: Spawn status: SpawnModel: Successfully spawned entity
              [ INFO] [1561399402.078652554, 0.353000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
                         [mpo_700_spawn-4] process has finished cleanly
                                                                       log file: /home/yusseff/.ros/log/591e6e84-96aa-11e9-9990-38378bf463ab/mpo_700_spawn-4*.log
 [teleop_keyboard-8] process has finished cleanly
log file: /home/yusseff/.ros/log/591e6e84-96aa-11e9-9990-38378bf463ab/teleop_keyboard-8*.log

**Comment by padhupradheep** [comment]
Hey Yussef! 

Thanks for opening the issue! 

I guess you have cloned the packages from the branch indigo. Please clone the packages from  [melodic](https://github.com/neobotix/neo_simulation/tree/melodic) and then try it again. 

Hope this helps! 

P.S: It is good that you opened the issue, but this repository is a standalone package for the robot. If you have any issues further, please open it in our [neo simulation](https://github.com/neobotix/neo_simulation) (exclusively created for our simulation) so this may help others who has similar issues. Hope you understand. 

Cheers!

**Comment by YusseffRuiz** [comment]
It was indeed the issue, thanks a lot for the quick response. It was solved by using
"git checkout melodic"
In the git folder.
