### ISSUE TITLE
MPO-700 modle use in gazebo or beo_sim ulation error

### ISSUE THREAD

**Issue by J-J-Wang** [neobotix/neo_mpo_700#9]
i use the ros-kinetic, i install by https://docs.neobotix.de/display/ROSSim/Installation+on+Ubuntu ,but  when i roslaunch  neo_simulation simulation.launch.
i got the error,
Error [parser_urdf.cc:3408] Unable to call parseURDF on robot model

Error [parser.cc:309] parse as old deprecated model file failed.

PS:i add the parameter --inorder when xacro

**Comment by padhupradheep** [comment]
Sorry for a very delayed response. It is indeed a strange error. It is completely working fine from our side. 
Closing the issue for the inactivity. In case if the problem persists, please feel free to open the issue once again.
